### ISSUE TITLE
Typo on README

### ISSUE THREAD

**Issue by puertajulian** [smoqadam/tg-bot-youtube-downloader#1]
This line:
2.Call setWebhook by opening this url : https://api.telegram.org/API_TOKEN/setWebhook?url=https://yourdomain.com/index.php

Should be like this
2.Call setWebhook by opening this url : https://api.telegram.org/botAPI_TOKEN/setWebhook?url=https://yourdomain.com/index.php

Note the "bot" after https://api.telegram.org/ and before API_TOKEN

**Comment by smoqadam** [comment]
thanks
